name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install dev dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Run lint
        run: |
          pip install flake8
          flake8 . --max-line-length=120

#      - name: Run tests
#        run: |
#          pytest -q

      - name: Check insecure dependencies (safety scan)
        run: |
          pip install safety
          safety scan

      - name: Verify h11 version is >= 0.16.0
        run: |
          python - <<'EOF'
          import pkg_resources
          import sys

          try:
              ver = pkg_resources.get_distribution("h11").parsed_version
              if ver < pkg_resources.parse_version("0.16.0"):
                  print(f"h11 version is {ver}, which is < 0.16.0 (vulnerable).")
                  sys.exit(1)
              print("h11 version OK:", ver)
          except pkg_resources.DistributionNotFound:
              print("h11 not installed - check your dependencies")
              sys.exit(1)
          EOF

  docker-build-and-push:
    runs-on: ubuntu-latest
    needs: lint-and-test
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/master-calendar-py-bot:latest .

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/master-calendar-py-bot:latest

      - name: Test Docker container
        run: docker run --rm ${{ secrets.DOCKER_HUB_USERNAME }}/master-calendar-py-bot:latest python -c "print('Docker image works!')"
